---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: false
    latex_engine: pdflatex
    template: "svm-latex-memo.tex"
fontfamily: times
fontsize: 12pt
geometry: margin=1in
header-includes:
   - \linespread{1.05}

from: Adam Storch
to: Files
subject: "2022 Willamette River Spring Chinook Run and 2023 Forecast"
date: "`r format(as.Date('2012-08-13'), '%d %B, %Y')`"
memorandum: true
graphics: true
width: .3
logoposition: right
logo: "odfwLogo.png"
---
  
I remember when we broke up the first time  
Saying, "This is it, I've had enough," 'cause like  
We hadn't seen each other in a month  
When you said you needed space. (What?)  
Then you come around again and say  
"Baby, I miss you and I swear I'm gonna change, trust me."  
Remember how that lasted for a day?  
I say, "I hate you," we break up, you call me, "I love you."  

Ooh, we called it off again last night  
But ooh, this time I'm telling you, I'm telling you  

We are never ever ever getting back together,  
We are never ever ever getting back together,  
You go talk to your friends, talk to my friends, talk to me  
But we are never ever ever ever getting back together  

Like, ever...  

I'm really gonna miss you picking fights  
And me falling for it screaming that I'm right  
And you would hide away and find your peace of mind  
With some indie record that's much cooler than mine  

Ooh, you called me up again tonight  
But ooh, this time I'm telling you, I'm telling you  

We are never, ever, ever getting back together  
We are never, ever, ever getting back together  
You go talk to your friends, talk to my friends, talk to me (talk to me)  
But we are never ever ever ever getting back together  

Ooh, yeah, ooh yeah, ooh yeah  
Oh oh oh  

I used to think that we were forever ever  
And I used to say, "Never say never..."  
Uggg... so he calls me up and he's like, "I still love you,"  
And I'm like... "I just... I mean this is exhausting, you know, like,  
We are never getting back together. Like, ever"  

No!  

We are never ever ever getting back together  
We are never ever ever getting back together  
You go talk to your friends, talk to my friends, talk to me  
But we are never ever ever ever getting back together  

We, ooh, getting back together, ohhh,  
We, ooh, getting back together  

You go talk to your friends, talk to my friends, talk to me (talk to me)  
But we are never ever ever ever getting back together   


---

Songwriters: Taylor Swift / Max Martin / Johan Shellback  
We Are Never Ever Getting Back Together lyrics © Kobalt Music Publishing Ltd., Sony/ATV Music Publishing LLC  
Send hate mail to svmille@clemson.edu


<!-- ```{r echo=FALSE} -->
<!-- harv_rt_form = function(x) ifelse(is.na(x),"", sprintf("%.1f%%", x*100)) -->
<!-- harv_rt_formSm = function(x) ifelse(is.na(x),"", sprintf("%.2f%%", x*100)) -->
<!-- int_form = function(x) ifelse(is.na(x),"", formatC(x,digits = 0, format = "f", big.mark = ",")) -->
<!-- int_deci_form = function(x) ifelse(is.na(x),"", formatC(x,digits = 1, format = "f", big.mark = ",")) -->
<!-- year_form = function(x) ifelse(is.na(x),"", formatC(x,digits = 0, format = "f")) -->
<!-- ``` -->

<!-- ```{r include=FALSE} -->
<!-- myPaths <- .libPaths() # get the paths -->
<!-- myPaths <- c(myPaths[2], myPaths[1]) -->
<!-- .libPaths(myPaths) -->
<!-- .libPaths() -->
<!-- ``` -->

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->

<!-- packages <- c("tidyverse", -->
<!--               "gtools", -->
<!--               "lubridate", -->
<!--               "flextable", -->
<!--               "ggplot2", -->
<!--               "magrittr", -->
<!--               "officer", -->
<!--               "webshot", -->
<!--               "officedown", -->
<!--               "data.table", -->
<!--               "berryFunctions", -->
<!--               "scales") -->

<!-- if (!require(install.load)) { -->
<!--   install.packages("install.load") -->
<!-- } -->

<!-- install.load::install_load(packages) -->

<!-- # autonumTab <- run_autonum(seq_id = "tab", -->
<!-- #                           pre_label = "Table ", -->
<!-- #                           post_label = ". ", -->
<!-- #                           bkm_all = TRUE, -->
<!-- #                           prop = fp_text( -->
<!-- #                             color = "black", -->
<!-- #                             font.size = 12, -->
<!-- #                             bold = FALSE, -->
<!-- #                             italic = FALSE, -->
<!-- #                             underlined = FALSE, -->
<!-- #                             font.family = "Times New Roman", -->
<!-- #                             cs.family = NULL, -->
<!-- #                             eastasia.family = NULL, -->
<!-- #                             hansi.family = NULL, -->
<!-- #                             vertical.align = "baseline", -->
<!-- #                             shading.color = "transparent") -->
<!-- # ) -->
<!-- #  -->
<!-- # table.caption.format <- fp_par(text.align = "left", -->
<!-- #                   padding.bottom = 10) -->
<!-- # # autonumFig <- run_autonum(seq_id = "fig", pre_label = "Figure ", post_label = ". ", bkm_all = FALSE) -->
<!-- ``` -->

<!-- <!-- \newpage --> -->
<!-- <!-- # List of Tables --> -->
<!-- <!-- <!---BLOCK_TOC{style: 'Table Caption',seq_id: 'tab', separator: ','}---> --> -->
<!-- <!-- \newpage --> -->
<!-- <!-- # List of Figures --> -->
<!-- <!-- <!---BLOCK_TOC{style: 'Image Caption',seq_id: 'fig', separator: ','}---> --> -->
<!-- \newpage -->
<!-- # Introduction -->

<!-- This example document was generated by linking R directly to the TAC database and data from the FPC website.  As long as data from those sources are maintained, TAC products (e.g., management reports) can be updated with a handful of key strokes; as opposed to hours of spreadsheet manipulation. In addition to updating tables (as below), we can also update values in text.  For example,   -->

<!-- <!-- \newpage --> -->
<!-- <!-- ```{r tab.cap=paste("Harvest accounting for upriver spring Chinook (including Snake River summer Chinook), ",T1_mgmtRep[1,1],"–",T1_mgmtRep[nrow(T1_mgmtRep),1],".", sep=""), tab.id = "Table1", echo=FALSE, tab.cap.style = "Table Caption"} --> -->
<!-- <!-- flextable(T1_mgmtRep) %>% --> -->
<!-- <!--   align(align = "center", --> -->
<!-- <!--         part = "all") %>% --> -->
<!-- <!--   valign(i = 1, --> -->
<!-- <!--          valign = "bottom", --> -->
<!-- <!--          part = "header") %>% --> -->
<!-- <!--   set_header_labels(year = "Year", --> -->
<!-- <!--                     rm_run_size = "River Mouth Run Size", --> -->
<!-- <!--                     tot_nt_impacts = "Total Non-treaty Impacts", --> -->
<!-- <!--                     tot_treat_impacts = "Total Treaty Impacts", --> -->
<!-- <!--                     tot_all_treat_harvest_rate = "Total Allowed Treaty Harvest Rate", --> -->
<!-- <!--                     tot_all_treat_harv = "Total Allowed Treaty Harvest (catch balance for non-treaty)", --> -->
<!-- <!--                     tot_act_treat_harv_rate = "Total Actual Treaty Harvest Rate") %>% --> -->
<!-- <!--   set_formatter(year = year_form, --> -->
<!-- <!--                 rm_run_size = int_form, --> -->
<!-- <!--                 tot_nt_impacts = int_form, --> -->
<!-- <!--                 tot_treat_impacts = int_form, --> -->
<!-- <!--                 tot_all_harvest_rate = harv_rt_form, --> -->
<!-- <!--                 tot_all_treat_harv = int_form, --> -->
<!-- <!--                 tot_act_treat_harv_rate = harv_rt_form) %>% --> -->
<!-- <!--   fontsize(size = 10, --> -->
<!-- <!--            part = "all") %>% --> -->
<!-- <!--   font(fontname = "Times New Roman", --> -->
<!-- <!--        part = "all") %>% --> -->
<!-- <!--   border_remove() %>% --> -->
<!-- <!--   hline(i=1, --> -->
<!-- <!--         part="header", --> -->
<!-- <!--         border = fp_border(color="black", --> -->
<!-- <!--                            width = 1)) %>% --> -->
<!-- <!--   hline_top(part="header", --> -->
<!-- <!--             border = fp_border(color="black", --> -->
<!-- <!--                                width = 2)) %>% --> -->
<!-- <!--   hline_bottom(part="body", --> -->
<!-- <!--                border = fp_border(color="black", --> -->
<!-- <!--                                   width = 2)) %>% --> -->
<!-- <!--   width(j = 1:7, 1) %>% --> -->
<!-- <!--   bold(i = ~ tot_act_treat_harv_rate > tot_all_treat_harvest_rate,  --> -->
<!-- <!--        j = ~ tot_act_treat_harv_rate + tot_treat_impacts) %>% --> -->
<!-- <!--   add_footer_lines("Note: bold values indicate overage.") %>% --> -->
<!-- <!--   fontsize(size = 12, part = "footer") %>% --> -->
<!-- <!--   font(fontname = "Times New Roman", --> -->
<!-- <!--        part = "footer") %>% --> -->
<!-- <!--   padding(padding = 0, part = "footer") --> -->
<!-- <!--   # set_caption( --> -->
<!-- <!--   #   as_paragraph( --> -->
<!-- <!--   #     as_chunk(paste("Harvest accounting for upriver spring Chinook (including Snake River summer Chinook), ",T1_mgmtRep[1,1],"–",T1_mgmtRep[nrow(T1_mgmtRep),1],".", sep=""), --> -->
<!-- <!--   #              props = fp_text_default(font.family = "Times New Roman", --> -->
<!-- <!--   #                                      font.size = 12))), --> -->
<!-- <!--   #   align_with_table = FALSE, --> -->
<!-- <!--   #   word_stylename = "Table Caption", --> -->
<!-- <!--   #   fp_p = table.caption.format, --> -->
<!-- <!--   #   autonum = autonumTab) --> -->
<!-- <!-- ``` --> -->

